name: Our First Workflow
on: push
jobs:
  log:
    name: Console Log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release Notes
        uses: actions/github-script@v7
        with:
          script: |
            const packageJson = require('./package.json');
            const childProcess = require('node:child_process');
            const currentVersion = packageJson.version;
            const branch = childProcess.execSync('git symbolic-ref --short HEAD').toString().trim();
            const oldVersions = JSON.parse(childProcess.execSync('npm view '+ packageJson.name +' versions').toString().replaceAll('\'', '"'));
            const isPublished = oldVersions.includes(currentVersion);
            if (branch == 'main' || branch == 'master') {
              const publishTag = 'latest';
            } else if (branch.match(/(\d+\.|)\d+/)) {
              const publishTag = 'v'+branch.match(/(\d+\.|)\d+/)?.[0]+'-lts';
            } else {
              throw new Error('`publishTag` is not define.');
            }
            console.log(branch == 'main', branch == 'main' || branch == 'master', isPublished, publishTag);
