name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!'
  log:
    name: Console Log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release Notes
        uses: actions/github-script@v7
        with:
          script: |
            const childProcess = require('child_process');
            console.log(childProcess);
