name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: console.log
        uses: actions/github-script@v4
        with:
          script: |
            var package = require('./package.json');
            var ps = require('node:child_process');
            console.log(package);
