name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!'
  log:
    name: Console Log
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release Notes
        uses: actions/github-script@v7
        with:
          script: |
            const packageJson = require('./package.json');
            const childProcess = require('node:child_process');
            const branch = childProcess.execSync('git symbolic-ref --short HEAD');
            console.log(branch);
            # const oldVersions = childProcess.execSync('npm view '+ packageJson.name +' versions');
            # if (branch == 'main' || branch == 'master') {
            #   const publishTag = 'latest';
            # } else if (branch.match(/(\d+\.|)\d+/)) {
            #   const publishTag = 'v'+branch.match(/(\d+\.|)\d+/)?.[0]+'-lts';
            # }
            # console.log(oldVersions, type(oldVersions));
