name: Our First Workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    environment: os
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        if: false
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - id: step3
        env:
          MY_VAR: ${{ vars.AAA }}
        run: |
          echo $MY_VAR
