name: Our Test Workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        with: # Set the secret as an input
          super_secret: ${{ secrets.AAA }}
        run: echo "$super_secret"
