name: Our Test Workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output_1: ${{ steps.step1.outputs.test }}
      output_2: ${{ steps.step2.outputs.test }}
      output_3: ${{ steps.step3.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - id: step3
        uses: actions/github-script@v7
        with:
          script: |
            echo "test=awesome" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: [job1]
    steps:
      - run: echo '${{ toJSON(needs.job1.outputs) }}'
