name: Our Test Workflow
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    with: # Set the secret as an input
      super_secret: ${{ secrets.AAA }}
    steps:
      - id: step1
        run: echo "$super_secret"
